branch-defaults:
  master:
    environment: production
    group_suffix: null
global:
  application_name: GroceryGuruServer
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 17.03.1-ce
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
