shared:
  GOOGLE_MAPS_API_KEY: <%= ENV["GOOGLE_MAPS_API_KEY"] %>
  RECAPTCHA_SITE_KEY: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  RECAPTCHA_SECRET_KEY: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
  GOOGLE_OAUTH_CLIENT_ID: <%= ENV["GOOGLE_OAUTH_CLIENT_ID"] %>
  GOOGLE_OAUTH_CLIENT_SECRET: <%= ENV["GOOGLE_OAUTH_CLIENT_SECRET"] %>

development:
  secret_key_base: 2299dbe9ee995047fadecef7afac38eb37582e414fd0dde9aaafb3cc0d2de2b3bbdeaf892766bb9e7b4204678b2dfb6cdda80da437e6c975d1bc02817a543a1a

test:
  secret_key_base: 11d0bf1aefbf42e036c2a84366db8508bc96024ef0ebd80e48cd4d3cada6f6438f2f8f8ebf66ae72f660bb16c6e85b3883d52c7ac0686a61c9a3aa289df886b8

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
