# Sourced from https://en.wikipedia.org/wiki/List_of_department_stores_of_the_United_States
["99 cents only stores",
"albertsons",
"bj's wholesale club",
"bargain hunt",
"barneys",
"bealls",
"belk",
"ben franklin",
"bergdorf goodman",
"bergner's",
"bi-mart",
"big lots",
"bloomingdale's",
"boscov's",
"boston store",
"boyds",
"burlington coat factory",
"carson's",
"century 21",
"charleston department stores",
"costco",
"curacao",
"david m. brian  owned by mccaulou's",
"dd's discounts",
"dillard's",
"dollar general",
"dollar tree",
"dunham's department store",
"elder-beerman",
"family dollar",
"five below",
"flemington department store",
"food lion",
"fords federated store",
"fred meyer",
"fred's",
"fresh market",
"fry's food and drug",
"gabriel brothers",
"getz's",
"giant food stores",
"goody's",
"gordmans",
"gump's",
"gus mayer",
"halls",
"hannaford",
"harbor freight tools",
"harmons",
"harris teeter",
"herberger's",
"homegoods",
"hudson's bay company",
"hy-vee",
"j. c. penney",
"johns",
"jos. kuhn & co.",
"king's variety store",
"kmart",
"kohl's",
"kroger",
"la epoca",
"lavogue department store",
"leader department store",
"lord & taylor",
"lucky stores",
"mack & dave's department store",
"macy's",
"magic mart",
"marshalls",
"mccaulou's department store",
"meijer",
"murphy's",
"national stores",
"national wholesale liquidators",
"neilson's",
"neiman marcus",
"new york",
"nichols stores",
"norby's",
"nordstrom",
"ocean state job lot",
"ollie's bargain outlet",
"ossell's department store",
"palais royal",
"peebles",
"price chopper",
"pricerite",
"publix",
"ralphs",
"redner's markets",
"renys",
"roses",
"ross stores",
"ruben's",
"rubensteins",
"safeway inc.",
"saks fifth avenue",
"sam's club",
"save-a-lot",
"schroeder's",
"sears",
"shirokiya",
"shoprite",
"shopko",
"smith's",
"sprouts farmers market",
"stage stores inc.",
"stage",
"stahlke's",
"stein mart",
"stop and shop",
"t.j. maxx",
"target",
"the bon-ton",
"the fresh grocer",
"the sm store",
"tomah cash mercantile",
"tops markets",
"trader joe's",
"tuesday morning",
"von maur",
"vons",
"walmart",
"weaver's",
"wegmans",
"whole foods",
"wilson's",
"winn dixie",
"wise",
"young's department store",
"younkers"].each do |store_name|
  Store.find_or_create_by!(name: store_name.downcase)
end
puts "1/3 finished creating stores"

File.foreach(File.join(Rails.root, 'db', 'food_data', 'sr28asc', 'FD_GROUP.txt')) do |line|
  id, group_name = line.strip.gsub(/~/,'').split("^")
  Item::Group.find_or_create_by!(name: group_name.downcase, usda_id: id)
end
puts "2/3 finished creating item groups"

# Sourced from the USDA Nutrient DB
File.foreach(File.join(Rails.root, 'db', 'food_data', 'sr28asc', 'FOOD_DES.txt')) do |line|
  id, group_id, name_mode = line.scrub.strip.gsub(/~/,'').split("^")
  item_name, *mode = name_mode.split(", ")
  mode_name = mode.join(", ")
  group = Item::Group.find_by(usda_id: group_id)
  mode = Item::Mode.find_or_create_by!(name: mode_name.strip.downcase)
  Item.find_or_create_by!(name: item_name.strip.downcase, mode_id: mode.id, usda_id: id, group: group)
  puts "Created #{item_name.strip.downcase}"
end
puts "3/3 finished creating items and modes"
