# Sourced from https://en.wikipedia.org/wiki/List_of_department_stores_of_the_United_States
Store.create([
  { name: "99 cents only stores" },
  { name: "albertsons" },
  { name: "bj's wholesale club" },
  { name: "bargain hunt" },
  { name: "barneys" }, 
  { name: "bealls" },
  { name: "belk" },
  { name: "ben franklin" },
  { name: "bergdorf goodman" },
  { name: "bergner's" },
  { name: "bi-mart" },
  { name: "big lots" },
  { name: "bloomingdale's" },
  { name: "boscov's" },
  { name: "boston store" },
  { name: "boyds" },
  { name: "burlington coat factory" },
  { name: "carson's" },
  { name: "century 21" },
  { name: "charleston department stores" },
  { name: "costco" },
  { name: "costco" },
  { name: "curacao" },
  { name: "david m. brian  owned by mccaulou's" },
  { name: "dd's discounts" },
  { name: "dillard's" },
  { name: "dollar general" },
  { name: "dollar tree" },
  { name: "dunham's department store" },
  { name: "elder-beerman" },
  { name: "family dollar" },
  { name: "five below" },
  { name: "flemington department store" },
  { name: "food lion" },
  { name: "fords federated store" },
  { name: "fred meyer" },
  { name: "fred's" },
  { name: "fresh market" },
  { name: "fry's food and drug" },
  { name: "gabriel brothers" },
  { name: "getz's" },
  { name: "giant food stores" },
  { name: "goody's" },
  { name: "gordmans" },
  { name: "gump's" },
  { name: "gus mayer" },
  { name: "halls" },
  { name: "hannaford" },
  { name: "harbor freight tools" },
  { name: "harmons" },
  { name: "harris teeter" },
  { name: "herberger's" },
  { name: "homegoods" },
  { name: "hudson's bay company" },
  { name: "hy-vee" },
  { name: "j. c. penney" },
  { name: "johns" },
  { name: "jos. kuhn & co." },
  { name: "king's variety store" },
  { name: "kmart" },
  { name: "kohl's" },
  { name: "kroger" },
  { name: "la epoca" },
  { name: "lavogue department store" },
  { name: "leader department store" },
  { name: "lord & taylor" },
  { name: "lucky stores" },
  { name: "mack & dave's department store" },
  { name: "macy's" },
  { name: "magic mart" },
  { name: "marshalls" },
  { name: "mccaulou's department store" },
  { name: "meijer" },
  { name: "meijer" },
  { name: "murphy's" },
  { name: "national stores" },
  { name: "national wholesale liquidators" },
  { name: "neilson's" },
  { name: "neiman marcus" },
  { name: "new york" },
  { name: "nichols stores" },
  { name: "norby's" },
  { name: "nordstrom" },
  { name: "ocean state job lot" },
  { name: "ollie's bargain outlet" },
  { name: "ossell's department store" },
  { name: "palais royal" },
  { name: "peebles" },
  { name: "price chopper" },
  { name: "pricerite" },
  { name: "publix" },
  { name: "ralphs" },
  { name: "redner's markets" },
  { name: "renys" },
  { name: "roses" },
  { name: "ross stores" },
  { name: "ruben's" },
  { name: "rubensteins" },
  { name: "safeway inc." },
  { name: "saks fifth avenue" },
  { name: "sam's club" },
  { name: "save-a-lot" },
  { name: "schroeder's" },
  { name: "sears" },
  { name: "shirokiya" },
  { name: "shoprite" },
  { name: "shopko" },
  { name: "smith's" },
  { name: "sprouts farmers market" },
  { name: "stage stores inc." },
  { name: "stage" },
  { name: "stahlke's" },
  { name: "stein mart" },
  { name: "stop and shop" },
  { name: "t.j. maxx" },
  { name: "target" },
  { name: "target" },
  { name: "the bon-ton" },
  { name: "the fresh grocer" },
  { name: "the sm store" },
  { name: "tomah cash mercantile" },
  { name: "tops markets" },
  { name: "trader joe's" },
  { name: "tuesday morning" },
  { name: "von maur" },
  { name: "vons" },
  { name: "walmart" },
  { name: "walmart" },
  { name: "weaver's" },
  { name: "wegmans" },
  { name: "whole foods" },
  { name: "wilson's" },
  { name: "winn dixie" },
  { name: "wise" },
  { name: "young's department store" },
  { name: "younkers" }
])
